[package]
name = "web-scraper"
version = "0.1.0"
edition = "2021"
description = ""
authors = ["Bastian Asmussen <bastian@asmussen.tech>"]
readme = "README.md"
license-file = "LICNESE"

[dependencies]
