[package]
name = "web-scraper"
version = "0.1.0"
edition = "2021"
description = ""
authors = ["Bastian Asmussen <bastian@asmussen.tech>"]
readme = "README.md"
license-file = "LICNESE"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.23.1"
